//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACC_Demo.Resources.en {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACC_Demo.Resources.en.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted Commitments.
        /// </summary>
        public static string Dashboard_AcceptedCommitments {
            get {
                return ResourceManager.GetString("Dashboard_AcceptedCommitments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Active Requests.
        /// </summary>
        public static string Dashboard_ActiveRequests {
            get {
                return ResourceManager.GetString("Dashboard_ActiveRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string Dashboard_Hours {
            get {
                return ResourceManager.GetString("Dashboard_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Your Help.
        /// </summary>
        public static string Dashboard_OfferHelp {
            get {
                return ResourceManager.GetString("Dashboard_OfferHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Ledger.
        /// </summary>
        public static string Dashboard_RecentLedger {
            get {
                return ResourceManager.GetString("Dashboard_RecentLedger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Assistance.
        /// </summary>
        public static string Dashboard_RequestAssistance {
            get {
                return ResourceManager.GetString("Dashboard_RequestAssistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Time Credit.
        /// </summary>
        public static string Dashboard_TotalTimeCredit {
            get {
                return ResourceManager.GetString("Dashboard_TotalTimeCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All.
        /// </summary>
        public static string Dashboard_ViewAll {
            get {
                return ResourceManager.GetString("Dashboard_ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Ledger.
        /// </summary>
        public static string Dashboard_ViewLedger {
            get {
                return ResourceManager.GetString("Dashboard_ViewLedger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Panel.
        /// </summary>
        public static string Nav_Admin {
            get {
                return ResourceManager.GetString("Nav_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Requests.
        /// </summary>
        public static string Nav_BrowseRequests {
            get {
                return ResourceManager.GetString("Nav_BrowseRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post a Request.
        /// </summary>
        public static string Nav_CreateRequest {
            get {
                return ResourceManager.GetString("Nav_CreateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Nav_Home {
            get {
                return ResourceManager.GetString("Nav_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Nav_Login {
            get {
                return ResourceManager.GetString("Nav_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Nav_Logout {
            get {
                return ResourceManager.GetString("Nav_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Requests.
        /// </summary>
        public static string Nav_MyRequests {
            get {
                return ResourceManager.GetString("Nav_MyRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Nav_Profile {
            get {
                return ResourceManager.GetString("Nav_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Requests.
        /// </summary>
        public static string Sidebar_BrowseRequests {
            get {
                return ResourceManager.GetString("Sidebar_BrowseRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Sidebar_Dashboard {
            get {
                return ResourceManager.GetString("Sidebar_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Activity.
        /// </summary>
        public static string Sidebar_MyActivity {
            get {
                return ResourceManager.GetString("Sidebar_MyActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        public static string Sidebar_Navigation {
            get {
                return ResourceManager.GetString("Sidebar_Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Request.
        /// </summary>
        public static string Sidebar_PostRequest {
            get {
                return ResourceManager.GetString("Sidebar_PostRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Sidebar_Profile {
            get {
                return ResourceManager.GetString("Sidebar_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Ledger.
        /// </summary>
        public static string Sidebar_TimeLedger {
            get {
                return ResourceManager.GetString("Sidebar_TimeLedger", resourceCulture);
            }
        }
    }
}
